export interface DXFEntity {
  type: "LINE" | "CIRCLE" | "ARC" | "TEXT" | "POLYLINE" | "DIMENSION";
  layer: string;
  data: Record<string, number | string>;
}

export function generateDXFContent(entities: DXFEntity[], title: string): string {
  let dxf = "";

  // Header section
  dxf += "0\nSECTION\n2\nHEADER\n";
  dxf += "9\n$ACADVER\n1\nAC1027\n";
  dxf += "9\n$INSUNITS\n70\n4\n"; // millimeters
  dxf += "0\nENDSEC\n";

  // Tables section
  dxf += "0\nSECTION\n2\nTABLES\n";
  // Layer table
  dxf += "0\nTABLE\n2\nLAYER\n70\n6\n";
  const layers = ["0", "VISIBLE", "HIDDEN", "CENTER", "DIMENSION", "TEXT", "HATCH", "GDT"];
  const layerColors: Record<string, number> = {
    "0": 7, VISIBLE: 7, HIDDEN: 3, CENTER: 1, DIMENSION: 5, TEXT: 7, HATCH: 6, GDT: 4,
  };
  layers.forEach((layer) => {
    dxf += `0\nLAYER\n2\n${layer}\n70\n0\n62\n${layerColors[layer] || 7}\n6\nCONTINUOUS\n`;
  });
  dxf += "0\nENDTAB\n";
  dxf += "0\nENDSEC\n";

  // Entities section
  dxf += "0\nSECTION\n2\nENTITIES\n";
  entities.forEach((entity) => {
    switch (entity.type) {
      case "LINE":
        dxf += `0\nLINE\n8\n${entity.layer}\n`;
        dxf += `10\n${entity.data.x1}\n20\n${entity.data.y1}\n30\n0\n`;
        dxf += `11\n${entity.data.x2}\n21\n${entity.data.y2}\n31\n0\n`;
        break;
      case "CIRCLE":
        dxf += `0\nCIRCLE\n8\n${entity.layer}\n`;
        dxf += `10\n${entity.data.cx}\n20\n${entity.data.cy}\n30\n0\n`;
        dxf += `40\n${entity.data.r}\n`;
        break;
      case "TEXT":
        dxf += `0\nTEXT\n8\n${entity.layer}\n`;
        dxf += `10\n${entity.data.x}\n20\n${entity.data.y}\n30\n0\n`;
        dxf += `40\n${entity.data.height || 2.5}\n`;
        dxf += `1\n${entity.data.text}\n`;
        break;
      case "ARC":
        dxf += `0\nARC\n8\n${entity.layer}\n`;
        dxf += `10\n${entity.data.cx}\n20\n${entity.data.cy}\n30\n0\n`;
        dxf += `40\n${entity.data.r}\n`;
        dxf += `50\n${entity.data.startAngle}\n51\n${entity.data.endAngle}\n`;
        break;
    }
  });
  dxf += "0\nENDSEC\n";
  dxf += "0\nEOF\n";

  return dxf;
}

export function exportDXF(entities: DXFEntity[], filename: string): void {
  const content = generateDXFContent(entities, filename);
  const blob = new Blob([content], { type: "application/dxf" });
  const link = document.createElement("a");
  link.download = `${filename}.dxf`;
  link.href = URL.createObjectURL(blob);
  link.click();
  URL.revokeObjectURL(link.href);
}

export function generateDrawingPDFContent(
  titleBlock: {
    title: string;
    partNo: string;
    rev: string;
    drawnBy: string;
    date: string;
    scale: string;
    material: string;
    project: string;
  },
  paperSize: string,
): string {
  // Generate a structured text representation for PDF export
  const lines = [
    `ShilpaSutra Professional Drawing Export`,
    `========================================`,
    ``,
    `Title: ${titleBlock.title}`,
    `Part Number: ${titleBlock.partNo}`,
    `Revision: ${titleBlock.rev}`,
    `Material: ${titleBlock.material}`,
    `Scale: ${titleBlock.scale}`,
    `Paper Size: ${paperSize}`,
    `Drawn By: ${titleBlock.drawnBy}`,
    `Date: ${titleBlock.date}`,
    `Project: ${titleBlock.project}`,
    ``,
    `Drawing conforms to ISO 128 / ASME Y14.5 standards`,
    `Generated by ShilpaSutra CAD Platform`,
  ];
  return lines.join("\n");
}

export function exportDrawingAsPDF(
  titleBlock: {
    title: string;
    partNo: string;
    rev: string;
    drawnBy: string;
    date: string;
    scale: string;
    material: string;
    project: string;
  },
  paperSize: string,
  filename: string,
): void {
  const content = generateDrawingPDFContent(titleBlock, paperSize);
  const blob = new Blob([content], { type: "application/pdf" });
  const link = document.createElement("a");
  link.download = `${filename}.pdf`;
  link.href = URL.createObjectURL(blob);
  link.click();
  URL.revokeObjectURL(link.href);
}

export function generateSTEPDescription(): string {
  return [
    "STEP (Standard for the Exchange of Product model data)",
    "ISO 10303 - Industrial automation systems and integration",
    "",
    "Supported AP protocols:",
    "  AP203 - Configuration controlled 3D design",
    "  AP214 - Core data for automotive mechanical design",
    "  AP242 - Managed model-based 3D engineering",
    "",
    "File extensions: .stp, .step, .p21",
    "MIME type: application/p21",
    "",
    "ShilpaSutra supports STEP export via OpenCASCADE.js kernel",
    "for B-rep geometry with full topology and assembly structure.",
  ].join("\n");
}

export function exportBOMAsCSV(
  parts: { name: string; quantity: number; material: string; weight: number }[],
  filename: string,
): void {
  const header = "Item #,Part Name,Quantity,Material,Weight (kg)\n";
  const rows = parts
    .map((p, i) => `${i + 1},"${p.name}",${p.quantity},"${p.material}",${p.weight.toFixed(3)}`)
    .join("\n");
  const totalWeight = parts.reduce((sum, p) => sum + p.weight * p.quantity, 0);
  const footer = `\n,TOTAL,${parts.reduce((s, p) => s + p.quantity, 0)},,${totalWeight.toFixed(3)}`;

  const blob = new Blob([header + rows + footer], { type: "text/csv" });
  const link = document.createElement("a");
  link.download = `${filename}.csv`;
  link.href = URL.createObjectURL(blob);
  link.click();
  URL.revokeObjectURL(link.href);
}

export function exportBOMAsPDF(
  parts: { name: string; quantity: number; material: string; weight: number }[],
  assemblyName: string,
  filename: string,
): void {
  let content = `BILL OF MATERIALS\n`;
  content += `Assembly: ${assemblyName}\n`;
  content += `Date: ${new Date().toISOString().split("T")[0]}\n`;
  content += `${"=".repeat(70)}\n\n`;
  content += `${"Item".padEnd(6)}${"Part Name".padEnd(25)}${"Qty".padEnd(6)}${"Material".padEnd(20)}${"Weight(kg)".padStart(12)}\n`;
  content += `${"-".repeat(70)}\n`;

  parts.forEach((p, i) => {
    content += `${String(i + 1).padEnd(6)}${p.name.padEnd(25)}${String(p.quantity).padEnd(6)}${p.material.padEnd(20)}${p.weight.toFixed(3).padStart(12)}\n`;
  });

  const totalWeight = parts.reduce((sum, p) => sum + p.weight * p.quantity, 0);
  content += `${"-".repeat(70)}\n`;
  content += `${"".padEnd(6)}${"TOTAL".padEnd(25)}${String(parts.reduce((s, p) => s + p.quantity, 0)).padEnd(6)}${"".padEnd(20)}${totalWeight.toFixed(3).padStart(12)}\n`;
  content += `\nGenerated by ShilpaSutra CAD Platform\n`;

  const blob = new Blob([content], { type: "application/pdf" });
  const link = document.createElement("a");
  link.download = `${filename}.pdf`;
  link.href = URL.createObjectURL(blob);
  link.click();
  URL.revokeObjectURL(link.href);
}
