export interface EngineeringMaterial {
  id: string;
  name: string;
  category: string;
  density: number;          // kg/m³
  youngsModulus: number;    // GPa
  poissonRatio: number;
  yieldStrength: number;    // MPa
  ultimateStrength: number; // MPa
  thermalConductivity: number; // W/(m·K)
  cte: number;              // µm/(m·°C) — coefficient of thermal expansion
  color: string;            // hex
  metalness: number;        // 0–1 for PBR
  roughness: number;        // 0–1 for PBR
  notes?: string;
}

export const MATERIALS: EngineeringMaterial[] = [
  /* ── Steels ── */
  {
    id: "steel_mild",
    name: "Mild Steel (AISI 1020)",
    category: "Steel",
    density: 7870,
    youngsModulus: 200,
    poissonRatio: 0.29,
    yieldStrength: 210,
    ultimateStrength: 380,
    thermalConductivity: 51.9,
    cte: 11.7,
    color: "#78909C",
    metalness: 0.85,
    roughness: 0.45,
    notes: "General-purpose carbon steel",
  },
  {
    id: "steel_304",
    name: "Stainless Steel 304",
    category: "Steel",
    density: 8000,
    youngsModulus: 193,
    poissonRatio: 0.28,
    yieldStrength: 215,
    ultimateStrength: 505,
    thermalConductivity: 16.2,
    cte: 17.2,
    color: "#B0BEC5",
    metalness: 0.9,
    roughness: 0.2,
    notes: "Austenitic stainless, excellent corrosion resistance",
  },
  {
    id: "steel_316",
    name: "Stainless Steel 316L",
    category: "Steel",
    density: 8000,
    youngsModulus: 193,
    poissonRatio: 0.28,
    yieldStrength: 170,
    ultimateStrength: 485,
    thermalConductivity: 16.3,
    cte: 16.0,
    color: "#CFD8DC",
    metalness: 0.92,
    roughness: 0.18,
    notes: "Mo-bearing grade, superior pitting resistance",
  },
  {
    id: "steel_4340",
    name: "Alloy Steel 4340",
    category: "Steel",
    density: 7850,
    youngsModulus: 205,
    poissonRatio: 0.29,
    yieldStrength: 470,
    ultimateStrength: 745,
    thermalConductivity: 44.5,
    cte: 12.3,
    color: "#607D8B",
    metalness: 0.88,
    roughness: 0.4,
    notes: "High-strength alloy steel, aerospace/defense",
  },
  {
    id: "steel_d2",
    name: "Tool Steel D2",
    category: "Steel",
    density: 7700,
    youngsModulus: 210,
    poissonRatio: 0.28,
    yieldStrength: 1500,
    ultimateStrength: 1900,
    thermalConductivity: 20.0,
    cte: 10.5,
    color: "#546E7A",
    metalness: 0.95,
    roughness: 0.1,
    notes: "High-carbon high-chromium die steel",
  },
  /* ── Aluminum ── */
  {
    id: "al_6061",
    name: "Aluminum 6061-T6",
    category: "Aluminum",
    density: 2700,
    youngsModulus: 68.9,
    poissonRatio: 0.33,
    yieldStrength: 276,
    ultimateStrength: 310,
    thermalConductivity: 167,
    cte: 23.6,
    color: "#90A4AE",
    metalness: 0.85,
    roughness: 0.35,
    notes: "Most common structural aluminum",
  },
  {
    id: "al_7075",
    name: "Aluminum 7075-T6",
    category: "Aluminum",
    density: 2810,
    youngsModulus: 71.7,
    poissonRatio: 0.33,
    yieldStrength: 503,
    ultimateStrength: 572,
    thermalConductivity: 130,
    cte: 23.4,
    color: "#9E9E9E",
    metalness: 0.9,
    roughness: 0.25,
    notes: "Aerospace-grade, high strength-to-weight",
  },
  {
    id: "al_2024",
    name: "Aluminum 2024-T3",
    category: "Aluminum",
    density: 2780,
    youngsModulus: 73.1,
    poissonRatio: 0.33,
    yieldStrength: 324,
    ultimateStrength: 469,
    thermalConductivity: 121,
    cte: 23.2,
    color: "#BDBDBD",
    metalness: 0.88,
    roughness: 0.3,
    notes: "Aircraft fuselage & wing structures",
  },
  /* ── Titanium ── */
  {
    id: "ti_6al4v",
    name: "Titanium Ti-6Al-4V",
    category: "Titanium",
    density: 4430,
    youngsModulus: 113.8,
    poissonRatio: 0.34,
    yieldStrength: 880,
    ultimateStrength: 950,
    thermalConductivity: 6.7,
    cte: 8.6,
    color: "#78909C",
    metalness: 0.75,
    roughness: 0.55,
    notes: "Most widely used titanium alloy; aerospace & medical",
  },
  /* ── Copper & Brass ── */
  {
    id: "copper_pure",
    name: "Copper C10100",
    category: "Copper",
    density: 8960,
    youngsModulus: 117,
    poissonRatio: 0.34,
    yieldStrength: 70,
    ultimateStrength: 220,
    thermalConductivity: 391,
    cte: 17.0,
    color: "#B87333",
    metalness: 0.95,
    roughness: 0.2,
    notes: "Oxygen-free copper, excellent conductivity",
  },
  {
    id: "brass_360",
    name: "Brass C36000",
    category: "Brass",
    density: 8490,
    youngsModulus: 97,
    poissonRatio: 0.34,
    yieldStrength: 124,
    ultimateStrength: 338,
    thermalConductivity: 115,
    cte: 20.5,
    color: "#D4AF37",
    metalness: 0.9,
    roughness: 0.25,
    notes: "Free-machining brass, CNC parts",
  },
  /* ── Plastics ── */
  {
    id: "pla",
    name: "PLA (3D Print)",
    category: "Plastics",
    density: 1240,
    youngsModulus: 3.5,
    poissonRatio: 0.36,
    yieldStrength: 55,
    ultimateStrength: 65,
    thermalConductivity: 0.13,
    cte: 68,
    color: "#E0E0E0",
    metalness: 0,
    roughness: 0.7,
    notes: "Biodegradable FDM filament",
  },
  {
    id: "abs",
    name: "ABS Plastic",
    category: "Plastics",
    density: 1050,
    youngsModulus: 2.1,
    poissonRatio: 0.38,
    yieldStrength: 40,
    ultimateStrength: 45,
    thermalConductivity: 0.17,
    cte: 90,
    color: "#EEEEEE",
    metalness: 0,
    roughness: 0.65,
    notes: "Common injection molding resin",
  },
  {
    id: "nylon_pa66",
    name: "Nylon PA66",
    category: "Plastics",
    density: 1140,
    youngsModulus: 3.2,
    poissonRatio: 0.41,
    yieldStrength: 82,
    ultimateStrength: 82,
    thermalConductivity: 0.26,
    cte: 80,
    color: "#F5F5F5",
    metalness: 0,
    roughness: 0.75,
    notes: "Engineering thermoplastic, good wear resistance",
  },
  {
    id: "peek",
    name: "PEEK",
    category: "Plastics",
    density: 1320,
    youngsModulus: 3.6,
    poissonRatio: 0.40,
    yieldStrength: 100,
    ultimateStrength: 110,
    thermalConductivity: 0.25,
    cte: 47,
    color: "#D7CCC8",
    metalness: 0,
    roughness: 0.5,
    notes: "High-performance polymer, continuous use to 250°C",
  },
  /* ── Wood ── */
  {
    id: "oak",
    name: "Oak (White)",
    category: "Wood",
    density: 770,
    youngsModulus: 11.0,
    poissonRatio: 0.35,
    yieldStrength: 50,
    ultimateStrength: 85,
    thermalConductivity: 0.16,
    cte: 5.4,
    color: "#8D6E63",
    metalness: 0,
    roughness: 0.85,
    notes: "Hardwood, furniture & flooring",
  },
  {
    id: "plywood",
    name: "Plywood (Birch)",
    category: "Wood",
    density: 650,
    youngsModulus: 7.0,
    poissonRatio: 0.3,
    yieldStrength: 30,
    ultimateStrength: 45,
    thermalConductivity: 0.12,
    cte: 4.0,
    color: "#BCAAA4",
    metalness: 0,
    roughness: 0.9,
    notes: "Structural plywood panels",
  },
  /* ── Composites ── */
  {
    id: "cfrp",
    name: "CFRP (0/90 Woven)",
    category: "Composites",
    density: 1580,
    youngsModulus: 70,
    poissonRatio: 0.3,
    yieldStrength: 600,
    ultimateStrength: 800,
    thermalConductivity: 5.0,
    cte: 2.0,
    color: "#212121",
    metalness: 0.05,
    roughness: 0.6,
    notes: "Carbon fiber reinforced polymer, quasi-isotropic",
  },
  {
    id: "gfrp",
    name: "GFRP (E-glass/Epoxy)",
    category: "Composites",
    density: 1850,
    youngsModulus: 20,
    poissonRatio: 0.28,
    yieldStrength: 250,
    ultimateStrength: 400,
    thermalConductivity: 0.35,
    cte: 14.0,
    color: "#E8F5E9",
    metalness: 0,
    roughness: 0.55,
    notes: "Glass-fibre composite, structural & marine",
  },
  /* ── Magnesium ── */
  {
    id: "mg_az31",
    name: "Magnesium AZ31B",
    category: "Magnesium",
    density: 1770,
    youngsModulus: 45,
    poissonRatio: 0.35,
    yieldStrength: 200,
    ultimateStrength: 260,
    thermalConductivity: 77,
    cte: 26.0,
    color: "#B0BEC5",
    metalness: 0.8,
    roughness: 0.5,
    notes: "Lightest structural metal alloy",
  },
  /* ── Ceramics ── */
  {
    id: "alumina",
    name: "Alumina (Al₂O₃ 99%)",
    category: "Ceramics",
    density: 3960,
    youngsModulus: 370,
    poissonRatio: 0.22,
    yieldStrength: 0,
    ultimateStrength: 380,
    thermalConductivity: 30,
    cte: 8.1,
    color: "#FAFAFA",
    metalness: 0.05,
    roughness: 0.3,
    notes: "Technical ceramic, wear parts & insulators",
  },
];

export const MATERIAL_CATEGORIES = Array.from(
  new Set(MATERIALS.map((m) => m.category))
);

export function getMaterialById(id: string): EngineeringMaterial | undefined {
  return MATERIALS.find((m) => m.id === id);
}

export function getMaterialsByCategory(category: string): EngineeringMaterial[] {
  return MATERIALS.filter((m) => m.category === category);
}

/** Compute estimated part weight given volume in mm³ */
export function computeWeight(materialId: string, volumeMm3: number): number {
  const mat = getMaterialById(materialId);
  if (!mat) return 0;
  // density is in kg/m³, volumeMm3 is mm³ → convert to m³ (×1e-9)
  return mat.density * volumeMm3 * 1e-9;
}
